image: node:16

stages:
  - install
  - build
  - test
  - deploy

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/tmp/Cypress'

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/
    - node_modules/
    - tmp/Cypress/

install:
  stage: install
  script:
    - npm install
  artifacts:
    name: "artifacts"
    paths:
      - .npm/
      - node_modules/
      - tmp/Cypress/

build:
  stage: build
  script:
    - CI=false npm run build
  artifacts:
    paths:
      - build

test:
  stage: test
  image: cypress/browsers:node16.5.0-chrome94-ff93
  script:
    - npm run e2e
  artifacts:
    paths:
      - cypress/screenshots
      - cypress/videos

deploy:
  stage: deploy
  script:
    - echo "Deploy stage is not configured yet"
